---
title: "initial-etl"
author: "Minh Ngo"
date: "2026-04-06"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


```{r}
library(tidyverse)

loans_raw <- read_csv("../data-raw/2024-pudb.csv")
```

```{r}
# Check missingness for borrower 2
borrower2_check <- loans_raw %>%
  mutate(
    b2_credit_missing = (Borrower2CreditScoreValue == 9),
    b2_age_missing = Borrower2AgeAtApplicationYears %in% c(998, 999),

    # define "borrower 2 exists"
    b2_exists = !(b2_credit_missing & b2_age_missing)
  )

# Summary
borrower2_check %>%
  summarise(
    total_rows = n(),

    borrower2_exists = sum(b2_exists, na.rm = TRUE),
    pct_exists = mean(b2_exists, na.rm = TRUE),

    usable_credit = sum(!b2_credit_missing, na.rm = TRUE),
    pct_credit_available = mean(!b2_credit_missing, na.rm = TRUE),

    usable_age = sum(!b2_age_missing, na.rm = TRUE),
    pct_age_available = mean(!b2_age_missing, na.rm = TRUE)
  )

```


```{r}
cols_to_keep <- c(
  # IDs / context
  "Year",
  "LoanCharacteristicsID",
  "Bank",
  "FIPSStateNumericCode",
  "FIPSCountyCode",
  "CoreBasedStatisticalAreaCode",

  # Neighborhood / area context
  "CensusTractMinorityRatioPercent",
  "CensusTractMedFamIncomeAmount",
  "LocalAreaMedianIncomeAmount",
  "HUDMedianIncomeAmount",

  # Core borrower / loan financials
  "TotalMonthlyIncomeAmount",
  "LTVRatioPercent",
  "NoteRatePercent",
  "NoteAmount",
  "HousingExpenseRatioPercent",
  "TotalDebtExpenseRatioPercent",
  "Borrower1CreditScoreValue",
  "Borrower2CreditScoreValue",
  "PMICoveragePercent",

  # Loan characteristics
  "LoanPurposeType",
  "ProductCategoryName",
  "MortgageType",
  "ScheduledTotalPaymentCount",
  "LoanAmortizationMaxTermMonths",
  "MortgageLoanSellerInstType",
  "PropertyUsageType",
  "PropertyUnitCount",
  "PropertyType",

  # Borrower characteristics
  "BorrowerCount",
  "BorrowerFirstTimeHomebuyer",
  "Borrower1AgeAtApplicationYears",
  "Borrower2AgeAtApplicationYears",
  "Borrower1SexType",
  "Borrower2SexType",
  "Borrower1Race1Type",
  "Borrower2Race1Type",
  "EmploymentBorrowerSelfEmployed"
)

fhfa_master <- loans_raw %>%
  select(any_of(cols_to_keep))

head(fhfa_master)
```


```{r}
fhfa_clean <- fhfa_master %>%
  mutate(
    # Credit scores
    Borrower1CreditScoreValue = na_if(Borrower1CreditScoreValue, 9),
    Borrower2CreditScoreValue = na_if(Borrower2CreditScoreValue, 9),

    # Age
    Borrower1AgeAtApplicationYears = na_if(Borrower1AgeAtApplicationYears, 999),
    Borrower1AgeAtApplicationYears = na_if(Borrower1AgeAtApplicationYears, 998),
    Borrower2AgeAtApplicationYears = na_if(Borrower2AgeAtApplicationYears, 999),
    Borrower2AgeAtApplicationYears = na_if(Borrower2AgeAtApplicationYears, 998),

    # Race
    Borrower1Race1Type = ifelse(Borrower1Race1Type %in% c(6,7), NA, Borrower1Race1Type),
    Borrower2Race1Type = ifelse(Borrower2Race1Type %in% c(6,7), NA, Borrower2Race1Type),

    # Sex
    Borrower1SexType = ifelse(Borrower1SexType %in% c(3,4,6), NA, Borrower1SexType),
    Borrower2SexType = ifelse(Borrower2SexType %in% c(3,4,6), NA, Borrower2SexType)
  )
```

```{r}
fhfa_clean <- fhfa_clean %>%
  mutate(
    TotalMonthlyIncomeAmount = as.numeric(TotalMonthlyIncomeAmount),
    LTVRatioPercent = as.numeric(LTVRatioPercent),
    NoteRatePercent = as.numeric(NoteRatePercent),
    TotalDebtExpenseRatioPercent = as.numeric(TotalDebtExpenseRatioPercent),
    NoteAmount = as.numeric(NoteAmount)
  )
```

```{r}
summary(fhfa_clean)

```
```{r}
fhfa_clean2 <- fhfa_clean %>%
  mutate(
    # monthly income of 999999 is likely a cap / placeholder-like extreme
    TotalMonthlyIncomeAmount = if_else(
      TotalMonthlyIncomeAmount > 100000,
      NA_real_,
      TotalMonthlyIncomeAmount
    ),

    # LTV above 100 is possible in edge cases, but if you want a cleaner
    # modeling dataset, cap them to NA for now
    LTVRatioPercent = if_else(
      LTVRatioPercent > 100,
      NA_real_,
      LTVRatioPercent
    ),

    # guard against impossible nonpositive financial values
    TotalMonthlyIncomeAmount = if_else(
      TotalMonthlyIncomeAmount <= 0,
      NA_real_,
      TotalMonthlyIncomeAmount
    ),
    NoteAmount = if_else(
      NoteAmount <= 0,
      NA_real_,
      NoteAmount
    ),
    NoteRatePercent = if_else(
      NoteRatePercent <= 0,
      NA_real_,
      NoteRatePercent
    ),
    TotalDebtExpenseRatioPercent = if_else(
      TotalDebtExpenseRatioPercent < 0,
      NA_real_,
      TotalDebtExpenseRatioPercent
    ),
    HousingExpenseRatioPercent = if_else(
      HousingExpenseRatioPercent < 0,
      NA_real_,
      HousingExpenseRatioPercent
    )
  )


missing_summary_after <- tibble(
  variable = names(fhfa_clean2),
  missing_n = colSums(is.na(fhfa_clean2)),
  missing_pct = colSums(is.na(fhfa_clean2)) / nrow(fhfa_clean2) * 100
) %>%
  arrange(desc(missing_n))

missing_summary_after
```
```{r}
fhfa_master_clean <- fhfa_clean2 %>%
  filter(
    !is.na(NoteRatePercent),
    !is.na(TotalMonthlyIncomeAmount),
    !is.na(LTVRatioPercent),
    !is.na(TotalDebtExpenseRatioPercent),
    !is.na(Borrower1CreditScoreValue)
  )
```

```{r}
fhfa_master_clean <- fhfa_master_clean %>%
  mutate(
    min_credit_score = pmin(
      Borrower1CreditScoreValue,
      Borrower2CreditScoreValue,
      na.rm = TRUE
    ),
    min_credit_score = ifelse(is.infinite(min_credit_score), NA, min_credit_score),

    avg_age = rowMeans(
      cbind(Borrower1AgeAtApplicationYears, Borrower2AgeAtApplicationYears),
      na.rm = TRUE
    ),
    avg_age = ifelse(is.nan(avg_age), NA, avg_age)
  )
```

```{r}
fhfa_master_clean <- fhfa_master_clean %>%
  mutate(
    TotalMonthlyIncomeAmount = ifelse(TotalMonthlyIncomeAmount > 100000, NA, TotalMonthlyIncomeAmount),
    LTVRatioPercent = ifelse(LTVRatioPercent > 100, NA, LTVRatioPercent)
  ) %>%
  filter(
    !is.na(TotalMonthlyIncomeAmount),
    !is.na(LTVRatioPercent)
  )

missing_summary_after <- tibble(
  variable = names(fhfa_master_clean),
  missing_n = colSums(is.na(fhfa_master_clean)),
  missing_pct = colSums(is.na(fhfa_master_clean)) / nrow(fhfa_master_clean) * 100
) %>%
  arrange(desc(missing_n))

missing_summary_after
```


```{r}
write_csv(fhfa_master_clean, "../data-clean/pudb_master_clean.csv")
```